# -*- coding: utf-8 -*-
"""Pneumonia Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6st2yDXi2sx6cerWZW4z0RED44sDgcn
"""

import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from tensorflow.keras.preprocessing import image
import os
import matplotlib.pyplot as plt
import cv2

image_dims = 128
batch_size = 64

model = Sequential()

model.add(Conv2D(64 , (3,3) , activation = 'relu' , input_shape= (image_dims, image_dims, 3)))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64 , (3,3) , activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64 , (3,3) , activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

model.summary()

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

input_path = '/content/drive/MyDrive/chest_xray/'

training_data_generator =  ImageDataGenerator(rescale = 1./255,
                                             shear_range = 0.2,
                                             zoom_range = 0.2,
                                             horizontal_flip= True)

training_gen = training_data_generator.flow_from_directory(directory=input_path+'train',
                                                          target_size=(image_dims,image_dims),
                                                          batch_size=batch_size,
                                                          class_mode='binary')

from google.colab import drive
drive.mount('/content/drive')

validation_gen = validation_data_generator.flow_from_directory(
    directory= input_path + 'test',
    target_size=(image_dims, image_dims),
    batch_size=batch_size,
    class_mode='binary'
)

#Finding model accuracy
epochs = 10
history = model.fit(
    training_gen,
    steps_per_epoch= len(training_gen),
    epochs=epochs,
    validation_data=validation_gen,
    validation_steps=len(validation_gen)
)

plt.figure(figsize=(8,6))
plt.title('Accuracy scores')
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.legend(['accuracy', 'val_accuracy'])
plt.show()

plt.figure(figsize=(8,6))
plt.title('Loss value')
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.legend(['loss', 'val_loss'])
plt.show()

eval_result = model.evaluate(test_gen)

print('Loss rate at evaluation data:', eval_result[0])
print('Accuracy rate at evaluation data:', eval_result[1])

model.save('Pneumonia_Detection_model.keras')